name: yogi
on:
  push:
    branches:
      - master # 메인이 되는 브랜치명

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 설치
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # /home/runner/work/spring-blog-v2-step12/spring-blog-v2-step12/deploy 생성
      # cp build/libs/*.jar deploy/application.jar (복사하면서 명령어로 이름을 바꾼다)
      # cp Procfile deploy/Procfile (실행 시 prod 로 실행 되도록 하는 명령을 넣은 파일을 복사한다)
      # cp -r .ebextensions deploy/.ebextensions (숨김 파일을 생성한다)
      # cd deploy && zip -r deploy.zip . (복사한 데이터를 모두(.) 압축한다)
      - name: deploy packaging
        run: |
          mkdir deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r deploy.zip .

      # 눈으로 체크
      - name: list
        run: ls